# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-nm
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-nm
spec:
  ports:
  - port: 8040
    name: ipc
  - port: 8042
    name: web
  clusterIP: None
  selector:
    app: {{ include "hadoop.name" . }}
    release: {{ .Release.Name }}
    component: yarn-nm

#13562/tcp open  unknown
#43191/tcp open  unknown
